# Site settings
title: QNIB Solutions
email: christian@qnib.org
description: "All things IT to enhance the usage of infrastructure and software stacks."
baseurl: ""
url: "http://www.qnib.org"
twitter_username: CQnib
github_username:  ChristianKniep
collections:
  slots:
    output: true

# Build settings
#permalink: pretty
permalink: /:categories/:year/:month/:day/:title/index.html

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
