# Site settings
title: QNIB Inc
email: christian@qnib.org
description: "Blog about all things that cross my IT mind related to enhance the usage of infrastructure and software stacks."
baseurl: ""
url: "http://www.qnib.inc"
twitter_username: CQnib
github_username:  ChristianKniep

# Build settings
markdown: kramdown
permalink: pretty
