# Site settings
title: QNIB Solutions
email: christian@qnib.org
description: "All things IT to enhance the usage of infrastructure and software stacks."
baseurl: ""
url: "http://www.qnib.qnib"
twitter_username: CQnib
github_username:  ChristianKniep

# Build settings
permalink: pretty

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
