# Site settings
title: QNIB Solutions
email: christian@qnib.org
description: "All things IT to enhance the usage of infrastructure and software stacks."
baseurl: ""
url: "http://www.qnib.qnib"
twitter_username: CQnib
github_username:  ChristianKniep

# Build settings
markdown: kramdown
permalink: pretty
